### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by samchugit** [Inokinoki/kdeconnect-ios#1]
@Inokinoki Thanks for your work. And is there any update or alpha test?

**Comment by Inokinoki** [comment]
You can build it from source now, it is basically usable.

**Comment by samchugit** [comment]
Thank you, but I don't have any Mac devices so I can't access to Xcode. Still thanks for your reply and work!

**Comment by Inokinoki** [comment]
You are welcome. Thanks for your following!

We will do a release once the community has approved it :)
