### ISSUE TITLE
Can't work with linux?

### ISSUE THREAD

**Issue by xxyangyoulin** [Inokinoki/kdeconnect-ios#2]
I built my own with xcode, but I can't find iphone in kdeconnect on Linux……

**Comment by xxyangyoulin** [comment]
After twists and turns, I was connected. Its connection stability is relatively poor

**Comment by Inokinoki** [comment]
Hi, could you please share your modification on the codebase?

I tested on an iPhone simulator, which works well. But no luck with a real device.
