### ISSUE TITLE
Compile error - missing Pods-acknowledgements.plist

### ISSUE THREAD

**Issue by supagu** [Inokinoki/kdeconnect-ios#4]
I checked out and did a pod install.

Trying to compile I get the following error:

`Build input file cannot be found: '/Users/fabian/Projects/kdeconnect-ios/Pods/Pods-acknowledgements.plist'`

Where does this file come from?

**Comment by Inokinoki** [comment]
Please see:
https://blog.inoki.cc/2020/04/18/KDEConnect-iOS-dev-dairy-1/#filepods-acknowledgementsplist-pods-resourcessh-not-found
