### ISSUE TITLE
Tailscale/Raw Address not Functioning. 

### ISSUE THREAD

**Issue by FedX-sudo** [Inokinoki/kdeconnect-ios#6]
I just installed Tailscale to try to get around blocks of LAN access on some public networks. However, the KDE Connect app can't find hosts over Tailscale. Everything in Tailscale works fine, and KDE Connect works fine, but they don't work together. It is normal behavior for devices to not auto-discover over Tailscale, but the raw address connection feature is not functioning either, I enter an IP addres and its added to the list but nothing else happens.

**Comment by Inokinoki** [comment]
Is it the SwiftUI version or the old UIKit version?
For SwiftUI ver, please login and report at https://bugs.kde.org/enter_bug.cgi?product=kdeconnect ios-application group

**Comment by FedX-sudo** [comment]
Thank you for getting back! The bug appears to have been fixed, not sure where the bug got fixed, but it is now fully functional over Tailscale. Thanks! 

P.S. I am unsure if this is SwiftUI or UIKit, it appears to be the latest official build if that helps.
